baseURL = "https://yixiuer.me/"
theme = "meme"
title = "一休儿的哲学博客 - Yixiuer.me"
languageCode = "zh-CN"
copyright = "在保留本文作者及本文链接的前提下，非商业用途随意转载分享。"
hasCJKLanguage = true

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

relativeURLs = true

enableGitInfo = true

pluralizeListTitles = false

summaryLength = 42

enableRobotsTXT = true

# pygmentsCodefences = true
# pygmentsUseClasses = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsOptions = "linenos=table"

# enableEmoji = true

footnoteReturnLinkContents = "↩"

# paginate = 5

# [related]
# threshold = 80
# includeNewer = true
# toLower = true
# [[related.indices]]
# name = "categories"
# weight = 100
# [[related.indices]]
# name = "tags"
# weight = 95
# [[related.indices]]
# name = "keywords"
# weight = 90
# [[related.indices]]
# name = "date"
# weight = 10
# pattern = "2006"

[frontmatter]
lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

[blackfriday]
smartypants = false
fractions = false
hrefTargetBlank = true
extensionsmask = ["hardLineBreak", "backslashLineBreak"]

# [languages.zh-cn]
# languageName = "中文"
# contentDir = "content/zh"
# weight = 1
# languageCode = "zh-CN"
# hasCJKLanguage = true
# copyright = "在保留本文作者及本文链接的前提下，非商业用途随意转载分享。"

# [languages.en-us]
# languageName = "English"
# contentDir = "content/en"
# weight = 2
# languageCode = "en-US"
# copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"
# [languages.en-us.taxonomies]
# # category = "categories"
# # tag = "tags"
# # name = "names"
# [[languages.en-us.menu.main]]
# url = "/about/"
# name = "About"
# weight = 7
# pre = "internal"
# post = "user-circle"
# identifier = "about"
# [[languages.en-us.menu.home]]
# url = "/about/"
# name = "About"
# weight = 1
# pre = "internal"
# identifier = "about"
# [languages.en-us.params]
# lineHeight = 1.618
# enableSmallCaps = true
# postWidth = 28
# enableJustify = false
# enableChinesePunctuationGlyphCorrection = false
# customFooter = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"

# uglyURLs = true

[permalinks]
# life = "/:sections/:slug/"
# tech = "/:sections/:slug/"
# categories = "/categories/:slug/"
tags = "/tags/:slug/"

[taxonomies]
# category = "categories"
tag = "tags"
# name = "names"

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[outputFormats.SectionsAtom]
mediaType = "application/atom+xml"
baseName = "atom"

[outputFormats.SectionsRSS]
mediaType = "application/rss+xml"
baseName = "rss"
# [outputFormats.NoUglyHTML]
# mediaType = "text/html"
# noUgly = "true"
# [outputFormats.NoUglyRSS]
# mediaType = "application/rss+xml"
# noUgly = "true"
# [outputFormats.NoUglyAtom]
# mediaType = "application/atom+xml"
# baseName = "atom"
# noUgly = "true"

# [outputs]
# page = ["HTML"]
# home = ["HTML", "Atom", "RSS", "SectionsAtom", "SectionsRSS"]
# section = ["NoUglyHTML", "NoUglyRSS", "NoUglyAtom"]
# # Not working below v0.57.0, see: https://github.com/gohugoio/hugo/issues/4528
# taxonomyTerm = ["NoUglyHTML", "NoUglyRSS"]
# taxonomy = ["NoUglyHTML", "NoUglyRSS"]

[outputs]
page = ["HTML"]
home = ["HTML", "SectionsAtom", "SectionsRSS"]
section = ["HTML"]
# Not working below v0.57.0, see: https://github.com/gohugoio/hugo/issues/4528
taxonomyTerm = ["HTML"]
taxonomy = ["HTML"]

[author]
name = "一休儿"
email = "yixiuer.me@gmail.com"
# Your description, Markdown supported, this theme noly
motto = "Viva La Vida"
# Your avatar, URL, this theme noly
avatar = "/icons/apple-touch-icon.png"
# URL, this theme noly, Default: baseURL
website = "https://yixiuer.me/"
twitter = ""
facebook = ""

# RSS & Atom limit
[services.rss]
limit = -1

[[menu.main]]
url = "/home/"
name = "首页"
weight = 1
pre = "internal"
post = "home"
identifier = "home"

[[menu.main]]
url = "/original/"
name = "想法"
weight = 2
pre = "internal"
post = "pagelines"
identifier = "original"

[[menu.main]]
url = "/poetry/"
name = "诗作"
weight = 3
pre = "internal"
post = "leaf"
identifier = "poetry"

[[menu.main]]
url = "/aphorism/"
name = "格言"
weight = 4
pre = "internal"
post = "balance-scale"
identifier = "aphorism"

[[menu.main]]
url = "/notes/"
name = "笔记"
weight = 5
pre = "internal"
post = "envira"
identifier = "notes"

[[menu.main]]
url = "/excerpt/"
name = "摘录"
weight = 6
pre = "internal"
post = "link"
identifier = "excerpt"

[[menu.main]]
url = "/about/"
name = "关于"
weight = 7
pre = "internal"
post = "user-circle"
identifier = "about"

# [[menu.home]]
# url = "/life/"
# weight = 1
# pre = "internal"
# post = "grav"
# identifier = "life"

# [[menu.home]]
# url = "/tech/"
# weight = 2
# pre = "internal"
# post = "wpexplorer"
# identifier = "tech"

# [[menu.home]]
# url = "/about/"
# weight = 3
# pre = "internal"
# post = "user-circle"
# identifier = "about"

[[menu.home]]
url = "/home/"
name = "Home"
weight = 1
pre = "internal"
identifier = "home"

[[menu.home]]
url = "https://t.me/yixiuer"
name = "Telegram"
weight = 2
pre = "external"
identifier = "telegram"

[[menu.home]]
url = "/atom.xml"
name = "Feed"
weight = 3
pre = "external"
identifier = "feed"

# [[menu.socials]]
# url = "https://github.com/yixiuer"
# name = "GitHub"
# weight = 1
# pre = "external"
# identifier = "github"

# [[menu.socials]]
# url = ""
# name = "Twitter"
# weight = 2
# pre = "external"
# identifier = "twitter"

# [[menu.socials]]
# url = ""
# name = "Music"
# weight = 3
# pre = "external"
# identifier = "music"

# [[menu.links]]
# url = "/"
# name = "HOME"
# weight = 1
# pre = "internal"
# identifier = "home"

# [[menu.links]]
# url = "/coldplay/"
# name = "Coldplay"
# weight = 2
# pre = "internal"
# identifier = "coldplay"

# [[menu.links]]
# url = "/atom.xml"
# name = "Feed"
# weight = 3
# pre = "external"
# identifier = "feed"

[params]
enableHeader = true
displayHeaderInHome = false

enableMenu = true
displayMenuInHome = false

# Use for Header, If true, Please put your SVG brand image to `SVG.toml`.
# If false, will use your Site Title as fallback.
# Unit: px
siteBrandSVG = true
siteBrandSVGWidth = 250
siteBrandSVGHeight = 100
siteBrandSVGFill = "#fff"

# Unit: em
siteBrandFontSize = 5
siteBrandFontColor = "#fff"

siteBrandBackgroundColor = "hsl(0, 0%, 0%)"
# siteBrandBackgroundImage = "linear-gradient(90deg, #f79533 0, #f37055 15%, #ef4e7b 30%, #a166ab 44%, #5073b8 58%, #1098ad 72%, #07b39b 86%, #6dba82 100%)"

# poetry, footage, posts, page
homeLayout = "footage"

# Layout poetry settings
# Markdown supported
homePoetry = []
# Unit: em
homeLinksPadding = 1

# Layout footage settings
homePoster = "https://gateway.pinata.cloud/ipns/yixiuer.me/images/reflection-of-tree-at-night-10s-720p.jpg"
homeVideoWebm = "https://gateway.pinata.cloud/ipns/yixiuer.me/videos/reflection-of-tree-at-night-10s-720p.webm"
homeVideoMp4 = "https://gateway.pinata.cloud/ipns/yixiuer.me/videos/reflection-of-tree-at-night-10s-720p.mp4"
homeLogo = "https://gateway.pinata.cloud/ipns/yixiuer.me/icons/android-chrome-512x512.png"
homeLogoLink = "/home/"
homeTitle = "一休儿的哲学博客"
homeMotto = "易·象·辞"
homeDescription = "一个关于哲学的博客，目标是构建一个宏大的体系"
homeKeywords = "关键词：真理、形而上学、哲学、物理、诗歌、酒神、尼采、《查拉图斯特拉如是说》、神话、未来、科幻、赛博朋克、反乌托邦、去中心化、开源、太空"
homeLinksDelimiter = "·"

# URL, For JSON-LD, Twitter Cards, Open Graph
siteLogo = "/icons/apple-touch-icon.png"
# For HTML meta
siteDescription = "一个关于哲学的博客，目标是构建一个宏大的体系。关键词：真理、形而上学、哲学、物理、诗歌、酒神、尼采、《查拉图斯特拉如是说》、神话、未来、科幻、赛博朋克、反乌托邦、去中心化、开源、太空。"
# If not set, will use site’s all taxonomy terms as default
siteKeywords = ["真理", "形而上学", "哲学", "物理", "诗歌", "酒神", "尼采", "《查拉图斯特拉如是说》", "神话", "未来", "科幻", "赛博朋克", "反乌托邦", "去中心化", "开源", "太空"]
# Keep this format, change the number
siteCreatedTime = "2018-02-01T13:42:10+08:00"
# If you enable `twitterCards`, then add your Twitter username
siteTwitter = ""
# If you enable `openGraph`, then add your Facebook username
siteFacebook = ""

# Category
# sections or categories
# Note: You must delete `categories` in `taxonomies` if you set `sections`.
categoryBy = "sections"

# Categories Page
# Note: You can NOT disable tree if you set categoryBy equal to `sections`.
enableTree = true
displayPosts = true
displayPostsCount = true

# Tags
enableTagCloud = true
fontUnit = "em"
largestFontSize = 2.5
smallestFontSize = 0.8

# Unit: em
# You can leave it empty ("") to fallback to default value: 42
listWidth = 36
displayListTitle = false
# https://gohugo.io/functions/format/
listDateFormat = "1 月 2 日"
# left / right
listDatePosition = "right"
groupByMonth = false
chineseZodiac = true
i18nYear = true
i18nMonth = true

# Taxonomy List
displayTaxonomyTermCount = true

# Override Hugo’s default value
mainSections = ["original", "poetry", "aphorism", "notes", "excerpt"]

# Post Sections
postSections = ["original", "poetry", "aphorism", "notes", "excerpt"]

# Feed
feedSections = ["original", "poetry", "aphorism", "notes", "excerpt"]
# If `true`, will add content to Atom; If `false`, won’t.
# Note: By default, will add summary to Atom as `summary`,
# and if Front Matter have a description, description
# will override summary as `summary`
includeContent = true

# Dark Mode
enableDarkMode = false
defaultTheme = "light"
# Note: If true and enableDarkMode equal to `true`,
# users can still get Dark Mode if their device’s system
# has enabled Dark Mode (`prefers-color-scheme: dark`).
hideThemeToggle = false
hideThemeToggleInHome = false

# Web App
# https://realfavicongenerator.net/
# Keep android-chrome-512x512.png, apple-touch-icon.png, mstile-150x150.png,
# safari-pinned-tab.svg, favicon.ico, site.webmanifest and delete others
# Move to ~/blog/static/icons/
# Move favicon.ico site.webmanifest to ~/blog/static/
# Rename site.webmanifest to manifest.json
# See https://github.com/w3c/manifest/issues/689
# See https://github.com/OneSignal/OneSignal-Website-SDK/issues/332
# Check and Modify manifest.json (/icons path)
themeColor = "#000"
# themeColorDark = "#1c1c21"
safariMaskColor = "#000"
msApplicationTileColor = "#fff"

# Head Meta, SEO & Social Discovery
# Note that you must set openGraph to `true` if you set twitterCards to `true`,
# or your Twitter Cards info would be incomplete.
jsonLD = true
openGraph = true
twitterCards = true
autoDetectImages = true

# InstantClick
enableInstantClick = true

enableServiceWorker = true

# I suggest you set `katex: true` in post’s Front Matter instead of here
enableKaTeX = false

enableComments = false
enableDisqus = false
disqusShortname = ""

enableGoogleAnalytics = true
# `gtag` or `analytics`
trackingCodeType = "gtag"
trackingID = "UA-121634055-1"

googleSiteVerification = ""

# https://developers.facebook.com/apps/
# Used for Open Graph
facebookAppID = ""

# Post

# Unit: second
duration = 0.5

# HSL color
primaryColorLight = "0, 0%, 0%"
# primaryColorDark = "201, 65%, 62%"

# Unit: em
# You can leave it empty ("") to fallback to default value: 42
postWidth = 28

# Do NOT Change this value!
# If one post is not original, set in that post’s Front Matter.
original = true

# Post Description
displayPostDescription = true

# Post Meta
enablePostMeta = false
# Works for home layout `posts` only
enablePostMetaInHome = true
postMetaDateFormat = "January 2"
displayPublishedDate = true
publishedDateIcon = "calendar-alt"
displayModifiedDate = true
modifiedDateIcon = "calendar-check"
# Note that it will not display if the date is zero (not set).
displayExpiredDate = true
expiredDateIcon = "calendar-times"
displayCategory = true
categoryIcon = "folder"
categoryDelimiter = "/"
displayWordCount = true
wordCountIcon = "pencil-alt"
displayReadingTime = true
readingTimeIcon = "clock"

# Table of Contents
enableTOC = false
displayTOCTitle = true
linkHeadingsToTOC = true

# Headings Anchor / Section Sign (Add section sign before headings)
enableHeadingsAnchor = true
# RegEX format, Defaut: 1-6 (1|2|3|4|5|6), h1-h6
headingsOpt = "2"
# `anchorIcon` has a higher priority than `anchorSymbol`
# Default: §
anchorSymbol = ""
anchorIcon = ""
enableAnchorLink = true
enableAnchorAutoHide = false

# Image / Video
# If true, will replace `title` with caption.
enableCaption = true
captionPrefix = "◎ "

# Image Hosting
# Only support absolute URLs relative to root,
# eg: /../../*.jpg
enableImageHost = false
imageHostURL = "https://example.com/"
# Use host URL for head meta tags also
headAlso = false

# Video Hosting
# Only support absolute URLs relative to root,
# eg: /../../*.mp4
enableVideoHost = true
videoHostURL = "https://gateway.pinata.cloud/ipfs/"

# Footnote
# Footnote Ref with Square Brackets `[]`
squareBrackets = true
# If true, will replace `footnoteReturnLinkContents` with icon.
footnoteReturnLinkIcon = "angle-up"
# If true, the automatically added `<hr>` will be deleted.
# (In fact, the separator you added will be removed. This
# will be very useful if you prefer to add `---` to separate
# the content from the footnote in the Markdown file.)
insertHrBySelf = true

# Markdown
# New Markdown Syntax: Emphasis Point `..text..`
enableEmphasisPoint = true

# Typography
# Fonts, Unit: px
fontSize = 18
# Unitless values: use this number multiplied by the element’s font size
# Apply to post paragraph & toc only
lineHeight = 2

# Any value is not set, fallback to `fontFamilyBody` it will.
# If you use SVG as your Site Brand, then leave this value empty.
fontFamilySiteBrand = ""
fontFamilyMenu = "'EB Garamond', 'Noto Serif SC', serif"
fontFamilyTitle = "'EB Garamond', 'Noto Serif SC', serif"
fontFamilyHeadings = "'EB Garamond', 'Noto Serif SC', serif"
fontFamilyCode = "'EB Garamond', STKaiti, 'Noto Serif SC', serif"
fontFamilyQuote = "'EB Garamond', STFangsong, 'Noto Serif SC', serif"
fontFamilyTOC = "'EB Garamond', STKaiti, 'Noto Serif SC', serif"
fontFamilyCaption = "'EB Garamond', STKaiti, 'Noto Serif SC', serif"
fontFamilyFooter = "'EB Garamond', STKaiti, 'Noto Serif SC', serif"
fontFamilyBody = "'EB Garamond', STShusong, 'Noto Serif SC', serif"

# https://fonts.google.com/
fontsLink = 'https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,700,700i|Noto+Serif+SC:400,500,700&display=swap&subset=chinese-simplified'

enableChinesePunctuationGlyphCorrection = true

# Post headings and contents title
enableSmallCaps = false

# Post first paragraph
enableDropCap = false
# Every paragraph after `<hr />` or `---` in Markdown
enableDropCapAfterHr = false
deleteHrBeforeDropCap = false

enableParagraphIndent = true
# margin or indent, globe setting, Front Matter: indent
paragraphStyle = "indent"

enableJustify = true

# Post Copyright
enablePostCopyright = false
displayPostCopyright = false

enablePostUpdatedBadge = false
displayUpdatedBadge = false
enableBadgeTitle = true
badgeTitlePrefix = "Updated @ "

enablePostGitInfo = false
displayPostGitInfo = false
repoURL = "https://github.com/yixiuer/yixiuer.me"
# or https://github.com/yixiuer/yixiuer.me/edit/master
repoEditURL = "https://github.com/yixiuer/yixiuer.me/blob/master"
gitIcon = "code-branch"
displayCommitHash = true
displayCommitMessage = true
msgIcon = "info"
displayFeedback = true
feedbackIcon = "question"
feedbackText = "Feedback"
displayEditLink = true
editIcon = "edit"
editText = "Edit Me?"

# Related Posts
enableRelatedPosts = false
displayRelatedPosts = false
relatedPostsNumber = 5
relatedPostsIcon = "plus-circle"

# Post tags
enablePostTags = false
postTagsIcon = "tag"

# Post minimal footer
enableMinimalFooter = false
enableAboutPageMinimalFooter = false

# Post nav
# Note: Designed from a spatial perspective rather than
#       a time perspective like most other themes do.
#       Therefore, you will get a newer post if you click
#       prev on the left; you will get a older post if
#       you click next on the right.
enablePostNav = true
postNavInSection = true

# Syntax Highlight
enableHighlight = false

# Back to Top
enableBackToTop = true
backToTopIcon = "arrow-up"
displayBackToTopInHome = false

# Footer
# Note: Home layout `poetry`, `footage`, and 404 page have no footer.
enableFooter = true
displayCopyrightSymbol = true
displaySiteCreatedYear = true
iconBetweenYearAndAuthor = "heart"
iconColor = "#ccc"
iconAnimation = false
displayPoweredBy = true
displaySiteCopyright = false
customFooter = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)"

# Multilingual
enableLangToggle = false
# Display LangToggle only when content is translated
autoHideLangToggle = true
hideLangToggleInHome = true

# Style & Script
enableFingerprint = false

# 404
fofPoster = "https://gateway.pinata.cloud/ipns/io-oi.me/images/reflection-of-tree-at-night-10s-720p.jpg"
fofVideoWebm = "https://gateway.pinata.cloud/ipns/io-oi.me/videos/reflection-of-tree-at-night-10s-720p.webm"
fofVideoMp4 = "https://gateway.pinata.cloud/ipns/io-oi.me/videos/reflection-of-tree-at-night-10s-720p.mp4"
