[build]
publish = "public"
command = "npm run build && npm run ipfs-deploy"

[context.production.environment]
HUGO_VERSION = "0.58.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://yixiuer.netlify.com/*"
  to = "https://yixiuer.me/:splat"
  force = true
[[redirects]]
  from = "/tags/"
  to = "/home/"
